language: python
python:
  - "3.6.4"
services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov


before_script:
  -psql -c 'create database MyDiary;' -U postgres
  -psql -c 'create table IF NOT EXISTS users (id serial primary key not null,username text,email text,password text);' -U postgres
  -psql -c 'create table IF NOT EXISTS entries (id serial primary key not null,title text,content text,date text);' -U postgres
# command to run tests

# command to run tests
script:
  - pytest --cov=app/
#

after_success:
  - coveralls