language: python
python:
  - "3.6.4"

before_script:
  - psql -c 'create database MyDiary;' -U postgres
  - psql -c 'create table IF NOT EXISTS users (id serial primary key not null,username text,email text,password text);' -U postgres
  - psql -c 'create table IF NOT EXISTS entries (id serial primary key not null,title text,content text,date text);' -U postgres


install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

# command to run tests
script:
  - pytest --cov=app/
#

after_success:
  - coveralls