language: python
python:
  - "3.6.4"
services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov


before_script:
  - psql -c 'create database MyDiary;' -U postgres

# command to run tests
script:
  - pytest --cov=app/
#

after_success:
  - coveralls